// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcV0eqbxk6RosFUh6rgQSXgiQCtf3b0GA',
    appId: '1:636237287158:web:7ef82b6c7ad721d6a2e6d7',
    messagingSenderId: '636237287158',
    projectId: 'khuta-6232',
    authDomain: 'khuta-6232.firebaseapp.com',
    storageBucket: 'khuta-6232.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcV0eqbxk6RosFUh6rgQSXgiQCtf3b0GA',
    appId: '1:636237287158:android:a3c87a3271cd8773a2e6d7',
    messagingSenderId: '636237287158',
    projectId: 'khuta-6232',
    storageBucket: 'khuta-6232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL0sYUPP-QbA8pUL6xcaAIQYvJrWPSQB0',
    appId: '1:636237287158:ios:f7c1d7b05637c1fda2e6d7',
    messagingSenderId: '636237287158',
    projectId: 'khuta-6232',
    storageBucket: 'khuta-6232.firebasestorage.app',
    iosBundleId: 'com.example.khuta',
  );
}
