// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqPh9zm8xeZR0JrnMSboRni3UTqRNS8HQ',
    appId: '1:706590459247:web:557df104f45f70254d949a',
    messagingSenderId: '706590459247',
    projectId: 'khuta-1febc',
    authDomain: 'khuta-1febc.firebaseapp.com',
    storageBucket: 'khuta-1febc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLeIgW22aVDsIq_wVQtBxQSnTFxjUjaI',
    appId: '1:706590459247:android:073c679891a780e84d949a',
    messagingSenderId: '706590459247',
    projectId: 'khuta-1febc',
    storageBucket: 'khuta-1febc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfiG6jzH-e2nwy-FHlcRSuNstMk5AuhSY',
    appId: '1:706590459247:ios:386ace763e49328f4d949a',
    messagingSenderId: '706590459247',
    projectId: 'khuta-1febc',
    storageBucket: 'khuta-1febc.firebasestorage.app',
    iosClientId: '706590459247-9nrglgv6ao4kfias142oobaa4adltp4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.khuta',
  );
}
